# Generated by Django 5.0.6 on 2024-06-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_deck_time_created_alter_deck_deck_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
