# Generated by Django 5.0.6 on 2024-07-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_card_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("easy", "Easy"),
                    ("medium", "Medium"),
                    ("hard", "Hard"),
                    ("xhard", "Extra Hard"),
                ],
                default="medium",
                max_length=10,
                null=True,
            ),
        ),
    ]
