# Generated by Django 5.0.6 on 2024-07-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_card_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("easy", "Easy"),
                    ("medium", "Medium"),
                    ("hard", "Hard"),
                    ("xhard", "Extra Hard"),
                    ("-", "-"),
                ],
                default="medium",
                max_length=10,
                null=True,
            ),
        ),
    ]
